# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PztJLV_Hqv4AGuNhhctKdtrzrPC6dSBX
"""

!pip install -q ultralytics

import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "ultralytics"])

import json
import logging
import random
import shutil
import time
import xml.etree.ElementTree as ET
from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import torch
import ultralytics
from ultralytics import YOLO

WORK_DIR = Path("/content/bccd_yolov8")
RAW_DIR = WORK_DIR / "raw"
DATA_DIR = WORK_DIR / "dataset"
RUNS_DIR = WORK_DIR / "runs"
LOG_FILE = WORK_DIR / "experiment.log"
REPO_URL = "https://github.com/Shenggan/BCCD_Dataset.git"
CLASS_NAMES = ["RBC", "WBC", "Platelets"]
SEED = 42
EPOCHS = 20
IMG_SIZE = 640
BATCH = 16

WORK_DIR.mkdir(parents=True, exist_ok=True)

logger = logging.getLogger("bccd")
logger.setLevel(logging.INFO)
logger.handlers.clear()
fmt = logging.Formatter("%(asctime)s | %(levelname)-7s | %(message)s", "%Y-%m-%d %H:%M:%S")
for handler in (logging.FileHandler(LOG_FILE, mode="w"), logging.StreamHandler(sys.stdout)):
    handler.setFormatter(fmt)
    logger.addHandler(handler)

random.seed(SEED)
torch.manual_seed(SEED)

logger.info("Python %s", sys.version.split()[0])
logger.info("PyTorch %s | Ultralytics %s", torch.__version__, ultralytics.__version__)
if torch.cuda.is_available():
    logger.info("GPU detected: %s", torch.cuda.get_device_name(0))
    device = 0
else:
    logger.warning("No GPU detected, training will be very slow. Switch the runtime to T4 GPU.")
    device = "cpu"

def download_dataset():
    if RAW_DIR.exists():
        shutil.rmtree(RAW_DIR)
    logger.info("Cloning BCCD dataset from %s", REPO_URL)
    subprocess.run(["git", "clone", "--depth", "1", "-q", REPO_URL, str(RAW_DIR)], check=True)
    logger.info("Download complete")


def voc_to_yolo(xml_path):
    root = ET.parse(xml_path).getroot()
    w = float(root.find("size/width").text)
    h = float(root.find("size/height").text)
    rows = []
    for obj in root.findall("object"):
        name = obj.find("name").text.strip()
        if name not in CLASS_NAMES:
            continue
        box = obj.find("bndbox")
        xmin = max(0.0, float(box.find("xmin").text))
        ymin = max(0.0, float(box.find("ymin").text))
        xmax = min(w, float(box.find("xmax").text))
        ymax = min(h, float(box.find("ymax").text))
        if xmax <= xmin or ymax <= ymin:
            continue
        xc = (xmin + xmax) / 2 / w
        yc = (ymin + ymax) / 2 / h
        bw = (xmax - xmin) / w
        bh = (ymax - ymin) / h
        rows.append(f"{CLASS_NAMES.index(name)} {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}")
    return rows


def build_yolo_dataset():
    if DATA_DIR.exists():
        shutil.rmtree(DATA_DIR)
    split_dir = RAW_DIR / "BCCD" / "ImageSets" / "Main"
    img_dir = RAW_DIR / "BCCD" / "JPEGImages"
    ann_dir = RAW_DIR / "BCCD" / "Annotations"
    stats = {}
    for split in ("train", "val", "test"):
        (DATA_DIR / "images" / split).mkdir(parents=True, exist_ok=True)
        (DATA_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)
        ids = [line.strip() for line in (split_dir / f"{split}.txt").read_text().splitlines() if line.strip()]
        n_imgs, n_boxes, skipped = 0, 0, 0
        class_counts = {c: 0 for c in CLASS_NAMES}
        for stem in ids:
            src_img = img_dir / f"{stem}.jpg"
            src_xml = ann_dir / f"{stem}.xml"
            if not src_img.exists() or not src_xml.exists():
                skipped += 1
                continue
            rows = voc_to_yolo(src_xml)
            shutil.copy(src_img, DATA_DIR / "images" / split / src_img.name)
            (DATA_DIR / "labels" / split / f"{stem}.txt").write_text("\n".join(rows))
            n_imgs += 1
            n_boxes += len(rows)
            for r in rows:
                class_counts[CLASS_NAMES[int(r.split()[0])]] += 1
        stats[split] = {"images": n_imgs, "boxes": n_boxes, "skipped": skipped, "per_class": class_counts}
        logger.info("Split %-5s | images=%d boxes=%d skipped=%d | %s", split, n_imgs, n_boxes, skipped, class_counts)

    yaml_path = DATA_DIR / "data.yaml"
    yaml_path.write_text(
        f"path: {DATA_DIR}\n"
        "train: images/train\n"
        "val: images/val\n"
        "test: images/test\n"
        f"nc: {len(CLASS_NAMES)}\n"
        f"names: {CLASS_NAMES}\n"
    )
    logger.info("Dataset config written to %s", yaml_path)
    return yaml_path, stats


download_dataset()
data_yaml, dataset_stats = build_yolo_dataset()

model = YOLO("yolov8s.pt")
logger.info("Starting training | epochs=%d imgsz=%d batch=%d seed=%d", EPOCHS, IMG_SIZE, BATCH, SEED)

t0 = time.time()
model.train(
    data=str(data_yaml),
    epochs=EPOCHS,
    imgsz=IMG_SIZE,
    batch=BATCH,
    device=device,
    seed=SEED,
    project=str(RUNS_DIR),
    name="train",
    exist_ok=True,
    workers=2,
    plots=True,
    verbose=True,
)
train_minutes = (time.time() - t0) / 60
logger.info("Training finished in %.1f minutes", train_minutes)

best_weights = RUNS_DIR / "train" / "weights" / "best.pt"
logger.info("Best weights: %s", best_weights)

best_model = YOLO(str(best_weights))
metrics = best_model.val(
    data=str(data_yaml),
    split="val",
    imgsz=IMG_SIZE,
    batch=BATCH,
    device=device,
    project=str(RUNS_DIR),
    name="val",
    exist_ok=True,
    plots=True,
)

summary = {
    "precision": float(metrics.box.mp),
    "recall": float(metrics.box.mr),
    "mAP50": float(metrics.box.map50),
    "mAP50_95": float(metrics.box.map),
    "per_class_AP50": {},
    "train_minutes": round(train_minutes, 2),
    "epochs": EPOCHS,
    "dataset": dataset_stats,
}
for idx, ap in zip(metrics.box.ap_class_index, metrics.box.ap50):
    summary["per_class_AP50"][metrics.names[int(idx)]] = float(ap)

logger.info("=" * 60)
logger.info("VALIDATION RESULTS")
logger.info("Precision     : %.4f", summary["precision"])
logger.info("Recall        : %.4f", summary["recall"])
logger.info("mAP@50        : %.4f", summary["mAP50"])
logger.info("mAP@50-95     : %.4f", summary["mAP50_95"])
for cls, ap in summary["per_class_AP50"].items():
    logger.info("AP@50 %-10s: %.4f", cls, ap)
logger.info("=" * 60)

summary_path = WORK_DIR / "results_summary.json"
summary_path.write_text(json.dumps(summary, indent=2))
logger.info("Summary saved to %s", summary_path)

val_dir = RUNS_DIR / "val"
train_dir = RUNS_DIR / "train"
figures = [
    (val_dir / "confusion_matrix.png", "Confusion Matrix"),
    (val_dir / "confusion_matrix_normalized.png", "Confusion Matrix (Normalized)"),
    (train_dir / "results.png", "Training Curves"),
    (val_dir / "PR_curve.png", "Precision-Recall Curve"),
]
for path, title in figures:
    if path.exists():
        plt.figure(figsize=(10, 8))
        plt.imshow(mpimg.imread(str(path)))
        plt.axis("off")
        plt.title(title)
        plt.tight_layout()
        plt.show()
    else:
        logger.warning("Figure not found: %s", path)

logger.info("Full log saved to %s", LOG_FILE)
logger.info("All artifacts are in %s", WORK_DIR)

shutil.make_archive("/content/bccd_results", "zip", str(WORK_DIR))
from google.colab import files
files.download("/content/bccd_results.zip")
